site_name: บอทหลายบาท
theme:
  name: material
  features:
    - navigation.instant
  font:
    text: Kanit
    code: Roboto Mono
  language: th
  logo: https://cdn.jsdelivr.net/gh/manybaht/manybaht.github.io@main/storages/images/avatar.webp
  favicon: https://cdn.jsdelivr.net/gh/manybaht/manybaht.github.io@main/storages/images/avatar.webp
  icon:
    repo: fontawesome/brands/github
  palette:
      scheme: slate
      primary: deep orange
      accent: amber
nav:
  - 'index.md'
  - 'start.md'
  - 'play.md'
  - 'music.md'
  - 'qa.md'
  - 'howtofix.md'
  - 'สถานะบอท': 'https://manybaht.statuspage.io/'
extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/manybahtpage
      name: Facebook@manybahtpage
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/manybahtpage
      name: Twitter@manybahtpage
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/manybahtpage
      name: Instagram@manybahtpage
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/Q3B76tWvnJ
      name: Discord@manybahtpage
    - icon: fontawesome/solid/paper-plane
      link: mailto:manybahtpage@gmail.com
      name: Email@manybahtpage
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
copyright: Manybaht Music Discord Bot | Manybahtpage
repo_url: https://github.com/manybaht/Manybaht-Discord-Bot-Doc
repo_name: manybaht/Manybaht-Discord-Bot-Doc
edit_uri: ""